# -*- mode: python ; coding: utf-8 -*-
#
# launcher.spec — Build the portable launcher
#
# This spec embeds the entire GridAnalyzer_payload/ directory as data
# inside a single-file executable. The launcher.py code handles extraction,
# execution, and cleanup.
#
# Prerequisites:
#   1. First build the payload: pyinstaller portable/build_portable.spec
#   2. Then build this launcher: pyinstaller portable/launcher.spec
#
import os

# Resolve the project root explicitly so PyInstaller can find files even when
# it changes the working directory while processing this spec.
ROOT = os.path.abspath(os.path.join(SPECPATH, '..'))

# Path to the payload generated by build_portable.spec
_payload_dir = os.path.join(ROOT, 'dist', 'GridAnalyzer_payload')

if not os.path.isdir(_payload_dir):
    raise FileNotFoundError(
        f"Payload directory not found: {_payload_dir}\n"
        f"Run 'pyinstaller portable/build_portable.spec' first!"
    )

# Bundle the entire payload directory
datas = [
    (_payload_dir, 'payload'),
]

a = Analysis(
    [os.path.join(ROOT, 'portable', 'launcher.py')],
    pathex=[ROOT],
    binaries=[],
    datas=datas,
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='GridAnalyzer_Portable',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    # runtime_tmpdir set to a fast local path for the launcher's own extraction
    runtime_tmpdir=None,
    console=False,          # ← NO CONSOLE WINDOW
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # Optional: set an icon
    # icon='assets/icon.ico',
)
